### ISSUE TITLE
32-bit crashes

### ISSUE THREAD

**Issue by sjoerd222888** [opentk/GLControl#10]
The GLControl seems not to work with 32-bit. When I run the OpenTK.WinForm.TestForm as 32-bit process the applications just exists immediately. In the Windows EventViewer I then see the following:

```
Faulting application name: OpenTK.WinForms.TestForm.exe, version: 1.0.0.0, time stamp: 0x60ef18c5
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc000041d
Fault offset: 0x00000001
Faulting process id: 0x2f64
Faulting application start time: 0x01d7905685e556d3
Faulting application path: C:\github\GLControl\OpenTK.WinForms.TestForm\bin\Debug\netcoreapp3.1\OpenTK.WinForms.TestForm.exe
Faulting module path: unknown
Report Id: cc3bdcfd-299b-4cea-89c7-ffa8a22a2e3d
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by seanofw** [comment]
There are lots of questions here.

- Did you compile it yourself or use a precompiled Nuget package?
- Is it compiled for 32 bit?
- Are you using a 32-bit build of OpenTK 4 with it?
- Are you using a 32-bit build of GLFW with the 32-bit build of OpenTK 4?
- What was the exception raised?
- What was the exception's stack trace?

**Comment by sjoerd222888** [comment]
What I did was checkout out this repository. Then I edited the csproj file of OpenTk.WinForm.TestFrom such that it looks like this:

```
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenTK.WinForms\OpenTK.WinForms.csproj" />
  </ItemGroup>

</Project>
```

To answer your questions:
    

- Did you compile it yourself or use a precompiled Nuget package?
  *The project reference the nuget packages from nuget.org*
- Is it compiled for 32 bit?
  *If IT refers to OpenTK.WinForms.TestForm.exe then yes. If you refer to OpenTK I would not know actually but I would have expected yes because if you build a nuget package you can add dependencies for x64 and x86 and I expected that the maintainer of the package takes care of such dependencies*
- Are you using a 32-bit build of OpenTK 4 with it? 
  *As said I use the one from the repo. The way you ask the question probably means this nuget package only works with x64 and the maintainer did no handle the unpacking of the dependencies for both processor architecture in his nuspec file.*
- Are you using a 32-bit build of GLFW with the 32-bit build of OpenTK 4?
  *I use what comes with the nuget package.*
- What was the exception raised?
  *No exception was raised the application stops immediately. You only see something in the Windows EventViewer and this I have already posted above*
- What was the exception's stack trace?
  *There is no exception and hence there is no stacktrace. The application just stopped working.*

**Comment by sjoerd222888** [comment]
I had a look at the nuget packages. Packages are created with [Paket](http://fsprojects.github.io/Paket/), that's nice :-). OpenTK.Core 4.6.4 seems to be a netstand2.1 library, not architecture specific, so should work on x64 and x86.  Also OpenTk.Graphics seems not architecture dependent. 

OpenTK.Redist.glfw seems to provide runtime specific files and includes files for both x64 and x86.

I cannot find where there should be an issue with 32-bit. Can you maybe elaborate where you would see the potential issue?
