### ISSUE TITLE
Design mode problem when subclassing.

### ISSUE THREAD

**Issue by IVTore** [opentk/GLControl#16]
I am building a class library with .Net 5.
Designer does its brilliant job by giving exception messages which goes nowhere :) .
Is it impossible to subclass GLControl?
I am using the wrapper approach as a workaround for now.

**Comment by NogginBops** [comment]
Are there any exception messages, any stack traces? Anything other we can use to diagnose the issue you are having?

To my knowledge it should be possible to subclass GLControl, but @seanofw might know more details.

**Comment by seanofw** [comment]
The GLControl _can_ be subclassed (it's not marked `sealed` for a reason), but some care must be taken when subclassing it:

- All of the OpenGL content is rendered into an OpenGL child window, for example, which complicates any custom rendering you may be attempting.
- The WinForms Designer doesn't support OpenGL rendering at all (the Designer uses DirectX for rendering, and DirectX and OpenGL will fight hard if you try to use both in the same place), so you have to be careful not to accidentally instantiate the child window when using the Designer.
- It's also very important to make sure that every `override` you add invokes the `base` method, or its behavior is both unspecified (and unpredictable).
- Finally, the lifecycle is much more complicated than an "ordinary" control, so you must take care not to depend on events and messages arriving in certain orders.

It's safest _not_ to subclass it and to instead bind to the events it raises, but there's no explicit _prohibition_ on doing so.  Just be aware that subclassing is effectively using it in "expert mode," so if you don't know WinForms and Win32 inside-out upside-down and backwards, you may run into trouble.

**Comment by IVTore** [comment]
Thank you for your enlightening answers.
Since I am not after being a winforms guru, (why restrict myself?) I will keep on wrapping approach, which is working fine.
