### ISSUE TITLE
.NET 7 support

### ISSUE THREAD

**Issue by ghost** [opentk/GLControl#33]
Hi

Is it possible to add .NET 7 support?
Since .NET Core is getting abandoned by microsoft

**Comment by NogginBops** [comment]
Anything that support `.net core 3.1` is also going to work in `.net 7` so this isn't really a problem. Or has WinForms had breaking changes in those versions?

**Comment by emulationgirl** [comment]
I don't know yet, but I open an issue if I find anything

**Comment by NogginBops** [comment]
I'm going to close this issue as it's not really an issue.
