### ISSUE TITLE
Multiple Controls, Separate Windows Question

### ISSUE THREAD

**Issue by mludlum** [opentk/GLControl#34]
I have a Windows app with OpenTK4.8.  I am using multiple GLControls but in separate windows.  I'm not serializing the rendering like the Multiple Control test you have.   I'm assuming each control has a separate GL context and that the two do not conflict with each other.  Is this correct, or do I have to make sure only one renders at a time?

I'm troubleshooting a random Invalid Operation error that only happens on certain machines, usually with Intel integrated graphics.

**Comment by seanofw** [comment]
In theory that should be fine and sounds correct. As long as you’re careful to switch contexts at the right times, there should be no overlap between their datasets.

I’m sorry to say that Intel integrated graphics is often glitchy in OpenGL in general. I’ve had stuff fail for very weird reasons. You can usually diagnose it with enough effort, but it’s not like the “It just works” you’re used to on other manufacturers’ GPUs 😒

**Comment by mludlum** [comment]
thanks for quick reply
