### ISSUE TITLE
Vector4.Transform issue

### ISSUE THREAD

**Issue by OnderCoskun16** [opentk/GLControl#38]
Hello 
I want to take from screen to world coordinate and i have found follow example

Vector4 clipCoordinates = new Vector4(normalizedX, normalizedY, -1.0f, 1.0f);
 Matrix4 invProjection = Matrix4.Invert(projection);
 Vector4 eyeCoordinates = Vector4.Transform(clipCoordinates, invProjection);   this line has error due to 	Argument 2: cannot convert from 'OpenTK.Mathematics.Matrix4' to 'OpenTK.Mathematics.Quaternion'	

Your library is   public static Vector4 Transform(Vector4 vec, Quaternion quat) but all of examples has   public static Vector4 Transform(Vector4 vec, Vector4 invprojection)

how can i find a solution this problem? 
Thank you for interesting

**Comment by NogginBops** [comment]
What version of GLControl and OpenTK are you using?

**Comment by OnderCoskun16** [comment]
<PackageReference Include="OpenTK" Version="4.8.1" />
I tried your example that called name OpenTK.WinForms.InputTest

**Comment by OnderCoskun16** [comment]
is there anyone can help the my question?

**Comment by NogginBops** [comment]
Sorry for the late reply.
Not sure where you got example code that contains `Vector4.Transform` but you are likely looking for `Vector4.TransformRow`.
If there is any resource where we are using `Vector4.Transform` it would be great if you could tell me where so I can fix that.

**Comment by OnderCoskun16** [comment]
Thank you for your interesting
I got the sample program from chat gp. 

But there is also a program I made myself. I found values between 0 and 1 as screen coordinates. How do I convert it to the coordinates of the object afterwards?

            var x = (2f * mouseX) / glControl.ClientSize.Width - 1f;
            var y = 1f - (2f * mouseY) / glControl.ClientSize.Height;
            var z = 1f;
            var rayNormalizedDeviceCoordinates = new Vector3(x, y, z);

            // 4D homogeneous clip coordinates
            var rayClip = new Vector4(rayNormalizedDeviceCoordinates.X, rayNormalizedDeviceCoordinates.Y, -1f, 1f);
            // 4D eye (camera) coordinates
            var rayEye = projection.Inverted() * rayClip;
            rayEye = new Vector4(rayEye.X, rayEye.Y, -1f, 0f);
            var nearPoint = rayEye;

            var direction = rayClip - rayEye;
            direction.Normalized()
            // 4D world coordinates
            var rayWorldCoordinates = (lookat.Inverted() * rayEye).Xyz;

**Comment by NogginBops** [comment]
Please find real examples instead of ones hallucinated by chat gpt. You could ask for support on our discord.

In the code you posted there it seems like the matrix multiplication order is wrong. OpenTK uses row-major matrix conventions where the matrix multiplication order is left to right i.e. `vec * matrix` instead of `matrix * vec`.
Not sure I understand your question though.

**Comment by OnderCoskun16** [comment]
Actually I wanna take from mouse coordinate to world coordinate. I didn't find anything about this on https://opentk.net/
