### ISSUE TITLE
Probleme with VBO and 2 GlControls on the same form

### ISSUE THREAD

**Issue by FrancisMartin-VB** [opentk/GLControl#7]
Hello,
I'm trying to run a Framework 4.8 project that works fine in Net.5. I have a VBO which is posted on 2 GLcontrols. In 5.0 impossible to display the VBO on the control added in 2nd on the form while the basic commands are well displayed. I created a 2nd VBO, a 2nd Shader but it didn't change anything. Have you ever encountered this problem and how to fix it?
Sincerely, Francis

![image](https://user-images.githubusercontent.com/81978881/115154872-5b6a9580-a07d-11eb-9a76-67a8775a8d91.png)

**Comment by seanofw** [comment]
I suspect this is about the OpenGL context:  When you create the GLControls, are you assigning them the same `SharedContext`?  If they don't share an OpenGL context, they won't be able to share data either.

**Comment by FrancisMartin-VB** [comment]
Hello,
Thank you for your reply. Effectively each control in its context. So I recreated the VBOs for each of them and it works great now.
cordially
